const b=require('/home/user/baileys-mod/lib')
const B=Buffer.isBuffer
const t=[]
const chk=(n,f,p)=>{try{const v=f();t.push((p(v)?'PASS':'FAIL')+' '+n)}catch(e){t.push('FAIL '+n+' threw '+e.message.slice(0,40))}}
;(async()=>{
chk('md5->Buffer',()=>b.md5(Buffer.from('x')),B)
t.push((B(await b.hkdf(Buffer.alloc(32),32,{info:'x'}))?'PASS':'FAIL')+' hkdf->Promise<Buffer>')
chk('callKdf len',()=>b.callKdf(Buffer.alloc(32),'l',16),v=>B(v)&&v.length===16)
t.push((B(await b.getMediaRetryKey(Buffer.alloc(32)))?'PASS':'FAIL')+' getMediaRetryKey->Promise<Buffer>')
chk('parseStun.isStun',()=>b.parseStun(Buffer.alloc(20)),v=>typeof v.isStun==='boolean')
chk('resolveVideoPreset',()=>b.resolveVideoPreset('720p'),v=>typeof v.width==='number')
chk('asciiDecode variadic',()=>b.asciiDecode(...b.asciiEncode('ab')),v=>v==='ab')
chk('buildBinding {packet,txId}',()=>b.buildBinding(),v=>B(v.packet)&&B(v.txId))
chk('waChatKey {key,compare}',()=>b.waChatKey(true),v=>typeof v.key==='function')
chk('WAJIDDomains.LID',()=>b.WAJIDDomains.LID,v=>v===1)
chk('WA_CERT_DETAILS no ISSUER',()=>b.WA_CERT_DETAILS,v=>v.ISSUER===undefined&&typeof v.SERIAL==='number')
chk('NACK no SenderReachout',()=>b.NACK_REASONS,v=>v.SenderReachoutTimelocked===undefined&&v.ParsingError===487)
chk('MEDIA_HKDF sticker-pack',()=>b.MEDIA_HKDF_KEY_MAPPING['sticker-pack'],v=>typeof v==='string')
chk("getDevice fallback 'baileys'",()=>b.getDevice('zz'),v=>v==='baileys')
chk('RetryReason NOT a runtime value',()=>('RetryReason' in b),v=>v===false)
chk('MRM has no parseRetryErrorCode',()=>b.MessageRetryManager.prototype.parseRetryErrorCode,v=>v===undefined)
chk('MRM has no clear',()=>b.MessageRetryManager.prototype.clear,v=>v===undefined)
chk('creds.advSecretKey string',()=>b.initAuthCreds().advSecretKey,v=>typeof v==='string')
chk('creds.noiseKey KeyPair',()=>b.initAuthCreds().noiseKey,v=>v&&v.public&&v.private)
chk('jidDecode bad -> undefined',()=>b.jidDecode('nope'),v=>v===undefined)
chk('getContentType(undef)',()=>b.getContentType(undefined),v=>v===undefined)
const mk=await b.mutationKeys(Buffer.alloc(32))
t.push((mk.indexKey&&mk.patchMacKey?'PASS':'FAIL')+' mutationKeys 5 keys')
console.log(t.join('\n'))
})()
